### ISSUE TITLE
Bugs regard to primary constructor

### ISSUE THREAD

**Issue by Deficuet** [serdedotnet/serde#313]
1. when names of parameter and field are identical
```C#
[GenerateSerde]
public partial class Test(Guid l3)
{
    public long l3;
}
```
The generated de logic considers the `long` field only but the value is then passed to the primary constructor, where the value tries to cast to the target type. Sometimes the unintended cast succeed silently, e.g. `long` to `float`.
```C#
Serde.Json.Test.Test Serde.IDeserialize<Serde.Json.Test.Test>.Deserialize(IDeserializer deserializer)
{
    long _l_l3 = default!;
    ...
    var newType = new Serde.Json.Test.Test(_l_l3) {
    ...
};
```
2. when names are different
```C#
[GenerateSerde]
public partial class Test(long l1)
{
    public long l3;
}
```
the Roslyn generator will fail due to the exception:
```
'ArgumentOutOfRangeException' with message 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'.
```
3. when the initialization of a field involves parameters in primary ctor
```C#
[GenerateSerde]
public partial class Test(long l2, long l3)
{
    public long l2;
    public long l3 = l3 / l2 + l3;
}
```
it does not compile because in the generated logic the init statement is directly copied:
```C#
Serde.Json.Test.Test Serde.IDeserialize<Serde.Json.Test.Test>.Deserialize(IDeserializer deserializer)
{
   long _l_l2 = default!;
   long _l_l3 = l3 / l2 + l3;

    byte _r_assignedValid = 0;
    ...
}
```
and the compiler would complain: `error CS0120: An object reference is required for the non-static field, method, or property 'Test.l2'`, etc.

Probably it is better to skip the fields that initialize with parameters from primary ctor, or consider only the parameters in the primary ctor if the ctor presents.

**Comment by agocke** [comment]
Oops -- I almost certainly just broke this in https://github.com/serdedotnet/serde/pull/312, I'll revert.

**Comment by agocke** [comment]
10.0.2 has been released that should fix this.
